### ISSUE TITLE
Admin area not translated

### ISSUE THREAD

**Issue by mstimvol** [elestio-examples/hoppscotch#1]
Thank you for this great package of Hoppscotch! Everything works fine for me, except one thing... when I login to the admin panel nothing is being translated:

![image](https://github.com/elestio-examples/hoppscotch/assets/67418257/65e6933f-4ca0-4283-9ea3-5cd33996cec7)

I figured out that this seems to be an issue in Hoppscotch (see https://github.com/hoppscotch/hoppscotch/issues/3379). But this issue has been resolved months ago. Any idea why it's still present in this version here?

**Comment by jbenguira** [comment]
hey @mstimvol we have published an updated image today that's fixing the issue
